package com.company.student_portal.domain.enums;

public enum NotificationType {
    // Assignment
    ASSIGNMENT_CREATED,
    ASSIGNMENT_UPDATED,
    ASSIGNMENT_DELETED,
    ASSIGNMENT_SUBMITTED,
    ASSIGNMENT_GRADED,
    ASSIGNMENT_DEADLINE_REMINDER,

    COURSE_ANNOUNCEMENT,
    NEW_MATERIAL_ADDED,
    MATERIAL_UPDATED,
    CLASS_SCHEDULE_CHANGED,

    ENROLLMENT_APPROVED,
    ENROLLMENT_REJECTED,
    ENROLLMENT_PENDING,
    NEW_COURSE_ENROLLED,

    MESSAGE_RECEIVED,
    COMMENT_ADDED,
    REPLY_ADDED,
    USER_MENTIONED,

    SYSTEM_UPDATE,
    MAINTENANCE,
    SECURITY_ALERT,
    PROFILE_UPDATED,
    PASSWORD_CHANGED,

}
